# Generated by Django 6.1.1 on 2026-10-03 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0004_providerprofile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='provider_profiles/'),
        ),
    ]
