# Generated by Django 6.1.1 on 2026-10-04 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0005_providerprofile_profile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='providerprofile',
            name='category',
        ),
    ]
