# Generated by Django 6.1.1 on 2026-10-04 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0006_remove_providerprofile_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='name',
            new_name='service_name',
        ),
    ]
