# Generated by Django 6.1.1 on 2026-10-06 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0007_rename_name_service_service_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofile',
            name='service_state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
