# Generated by Django 6.1.1 on 2026-10-06 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0008_providerprofile_service_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofile',
            name='service_district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
