# Generated by Django 6.1.1 on 2026-10-06 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0010_providerprofile_service_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofile',
            name='service_area',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
